
import { describe, it, expect } from 'vitest'
import { clampDayToMonth, expandRecurringConsumptions } from './recurrence'
import type { PFCardConsumption, PFCreditCard } from '@/db/schema'

describe('recurrence utils', () => {
    describe('clampDayToMonth', () => {
        it('should keep day if valid', () => {
            // Feb 15
            expect(clampDayToMonth(15, 2023, 2)).toBe(15)
        })

        it('should clamp 31st to 28th/29th of Feb', () => {
            // Feb 2023 (not leap)
            expect(clampDayToMonth(31, 2023, 2)).toBe(28)
            // Feb 2024 (leap)
            expect(clampDayToMonth(31, 2024, 2)).toBe(29)
        })

        it('should clamp 31st to 30th of April', () => {
            // April
            expect(clampDayToMonth(31, 2023, 4)).toBe(30)
        })
    })

    describe('expandRecurringConsumptions', () => {
        const mockCard: PFCreditCard = {
            id: 'card1',
            name: 'Test Card',
            bank: 'Bank',
            last4: '1234',
            closingDay: 25,
            dueDay: 5,
            network: 'VISA',
            currency: 'ARS',
            createdAt: ''
        }
        const cards = [mockCard]

        const baseConsumption: PFCardConsumption = {
            id: 'base1',
            cardId: 'card1',
            description: 'Netflix',
            amount: 1000,
            currency: 'ARS',
            purchaseDateISO: '2024-01-20',
            closingYearMonth: '2024-01', // Closes Jan 25
            postedYearMonth: '2024-02',
            createdAt: '',
            isRecurring: true,
            recurring: {
                freq: 'monthly',
                interval: 1,
                startDate: '2024-01-20',
                until: null
            },
            recurringId: 'series1'
        }

        it('should expand for next month', () => {
            // Target: Feb 2024 (Closes Feb 25)
            // Expect occurrence on Feb 20
            const expanded = expandRecurringConsumptions([baseConsumption], cards, '2024-02')
            expect(expanded).toHaveLength(1)
            expect(expanded[0].purchaseDateISO).toBe('2024-02-20')
            expect(expanded[0].closingYearMonth).toBe('2024-02')
            expect(expanded[0].id).toContain('::2024-02-20')
        })

        it('should NOT return anything for the base month (already exists)', () => {
            const expanded = expandRecurringConsumptions([baseConsumption], cards, '2024-01')
            expect(expanded).toHaveLength(0)
        })

        it('should handle end-of-month clamping', () => {
            const eomConsumption: PFCardConsumption = {
                ...baseConsumption,
                id: 'base2',
                purchaseDateISO: '2024-01-31',
                // Closes Feb 25! (Period Jan 26 - Feb 25)
                closingYearMonth: '2024-02'
            }

            // Checking Closing Month: Feb 2024
            // Base occurrence: Jan 31 (Generated by purchase). 
            // Is Jan 31 in Closing Feb? Yes (Jan 26-Feb 25).
            // Does expand return it? No (same date).
            const expandedFeb = expandRecurringConsumptions([eomConsumption], cards, '2024-02')
            expect(expandedFeb).toHaveLength(0)

            // Checking Closing Month: March 2024 (Feb 26 - Mar 25)
            // Next occurrence: '2024-02-29' (Leap).
            // Feb 29 -> Closes Mar 25? Yes, > Feb 25.
            const expandedMar = expandRecurringConsumptions([eomConsumption], cards, '2024-03')
            expect(expandedMar).toHaveLength(1)
            expect(expandedMar[0].purchaseDateISO).toBe('2024-02-29')
            expect(expandedMar[0].closingYearMonth).toBe('2024-03')
        })

        it('should respect "until" date', () => {
            const limitedConsumption: PFCardConsumption = {
                ...baseConsumption,
                recurring: {
                    ...baseConsumption.recurring!,
                    until: '2024-03-01'
                }
            }

            // Feb ok (Feb 20 < Mar 01)
            const expandedFeb = expandRecurringConsumptions([limitedConsumption], cards, '2024-02')
            expect(expandedFeb).toHaveLength(1)

            // March? Occurrence would be Mar 20. > Mar 01. Should skip.
            const expandedMar = expandRecurringConsumptions([limitedConsumption], cards, '2024-03')
            expect(expandedMar).toHaveLength(0)
        })
    })
})
